### ISSUE TITLE
App crashing with error when port is already in use

### ISSUE THREAD

**Issue by SaNch0sE** [ChechaValerii/Internship#4]
> [src/server/events.js](https://github.com/ChechaValerii/Internship/blob/master/lesson2/src/server/events.js)

Function `server.get('port')` in that file require a:
`const server = require('./server');`
in the beginning of the file, to work properly.

**Comment by ChechaValerii** [comment]
[fixed a51fac5 ](https://github.com/ChechaValerii/Internship/commit/5e3ea42085649988fcac1f10b6e6a5060b0b6cb0)
